package com.example.dicerollerapp

import androidx.compose.runtime.Composable
import androidx.compose.ui.res.stringResource


class Affirmations {

    val affirmations: List<String>
        @Composable
        get() {
            return listOf(
                    stringResource(R.string.affirmation1),
                    stringResource(R.string.affirmation2),
                    stringResource(R.string.affirmation3),
                    stringResource(R.string.affirmation4),
                    stringResource(R.string.affirmation5),
                    stringResource(R.string.affirmation6),
                    stringResource(R.string.affirmation7),
                    stringResource(R.string.affirmation8),
                    stringResource(R.string.affirmation9),
                    stringResource(R.string.affirmation10),
                    stringResource(R.string.affirmation11),
                    stringResource(R.string.affirmation12),
                    stringResource(R.string.affirmation13),
                    stringResource(R.string.affirmation14),
                    stringResource(R.string.affirmation15),
                    stringResource(R.string.affirmation16),
                    stringResource(R.string.affirmation17),
                    stringResource(R.string.affirmation18),
                    stringResource(R.string.affirmation19),
                    stringResource(R.string.affirmation20),
                    stringResource(R.string.affirmation21),
                    stringResource(R.string.affirmation22),
                    stringResource(R.string.affirmation23),
                    stringResource(R.string.affirmation24),
                    stringResource(R.string.affirmation25),
                    stringResource(R.string.affirmation26),
                    stringResource(R.string.affirmation27),
                    stringResource(R.string.affirmation28),
                    stringResource(R.string.affirmation29),
                    stringResource(R.string.affirmation30),
                    stringResource(R.string.affirmation31),
                    stringResource(R.string.affirmation32),
                    stringResource(R.string.affirmation33),
                    stringResource(R.string.affirmation34),
                    stringResource(R.string.affirmation35),
                    stringResource(R.string.affirmation36),
                    stringResource(R.string.affirmation37),
                    stringResource(R.string.affirmation38),
                    stringResource(R.string.affirmation39),
                    stringResource(R.string.affirmation40),
                    stringResource(R.string.affirmation41),
                    stringResource(R.string.affirmation42),
                    stringResource(R.string.affirmation43),
                    stringResource(R.string.affirmation44),
                    stringResource(R.string.affirmation45),
                    stringResource(R.string.affirmation46),
                    stringResource(R.string.affirmation47),
                    stringResource(R.string.affirmation48),
                    stringResource(R.string.affirmation49),
                    stringResource(R.string.affirmation50),
                    stringResource(R.string.affirmation51),
                    stringResource(R.string.affirmation52),
                    stringResource(R.string.affirmation53),
                    stringResource(R.string.affirmation54),
                    stringResource(R.string.affirmation55),
                    stringResource(R.string.affirmation56),
                    stringResource(R.string.affirmation57),
                    stringResource(R.string.affirmation58),
                    stringResource(R.string.affirmation59),
                    stringResource(R.string.affirmation60),
                    stringResource(R.string.affirmation61),
                    stringResource(R.string.affirmation62),
                    stringResource(R.string.affirmation63),
                    stringResource(R.string.affirmation64),
                    stringResource(R.string.affirmation65),
                    stringResource(R.string.affirmation67),
                    stringResource(R.string.affirmation68),
                    stringResource(R.string.affirmation69),
                    stringResource(R.string.affirmation70),
                    stringResource(R.string.affirmation71),
                    stringResource(R.string.affirmation72),
                    stringResource(R.string.affirmation73),
                    stringResource(R.string.affirmation74),
                    stringResource(R.string.affirmation75),
                    stringResource(R.string.affirmation76),
                    stringResource(R.string.affirmation77),
                    stringResource(R.string.affirmation78),
                    stringResource(R.string.affirmation79),
                    stringResource(R.string.affirmation80),
                    stringResource(R.string.affirmation81),
                    stringResource(R.string.affirmation82),
                    stringResource(R.string.affirmation83),
                    stringResource(R.string.affirmation84),
                    stringResource(R.string.affirmation85),
                    stringResource(R.string.affirmation86),
                    stringResource(R.string.affirmation87),
                    stringResource(R.string.affirmation88),
                    stringResource(R.string.affirmation89),
                    stringResource(R.string.affirmation90)
            )
        }

}